changes to fix flutter web
Fix flutter web error:

```
isValidPublicKey failed NoSuchMethodError: tried to call a non-function, such as null: 'core.BigInt.from' dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 318:50
```