changes to fix flutter web
When upgrading from 0.20.0 to 0.23.0 we found we couldn't call is `isValidAddress`. It would give the following error:

```
isValidPublicKey failed NoSuchMethodError: tried to call a non-function, such as null: 'core.BigInt.from' dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 318:50                _#from#tearOff
dart-sdk/lib/internal/iterable.dart 391:20                                        moveNext
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 748:20  next
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 586:14                of
dart-sdk/lib/core/iterable.dart 470:12                                            toList
packages/solana/src/rpc/rpc.dart.js 6161:121                                      isPointOnEd25519Curve
packages/solana/src/rpc/rpc.dart.js 6147:23                                       isValidAddress
...
```